-- Key mappings (set once, not in autocmd)
vim.keymap.set("n", "<leader>gg", ":Neogit<CR>", { desc = "Git" })
vim.keymap.set("n", "<leader>x", ":ccl<CR>", { desc = "Close quickfix/loclist" })
vim.keymap.set("n", "<leader>z", ":Neotree toggle<CR>", { desc = "Toggle file tree" })
vim.keymap.set("n", "<leader>t", ":TagbarToggle<CR>", { desc = "Toggle tagbar" })
vim.keymap.set("n", "<leader>y", ":tabprev<CR>", { desc = "Previous tab" })
vim.keymap.set("n", "<leader>u", ":tabfirst<CR>", { desc = "First tab" })
vim.keymap.set("n", "<leader>i", ":tablast<CR>", { desc = "Last tab" })
vim.keymap.set("n", "<leader>o", ":tabnext<CR>", { desc = "Next tab" })
vim.keymap.set("n", "<leader>w", ":w<CR>", { desc = "Save file" })
vim.keymap.set("n", "<leader>U", ":Atone<CR>", { desc = "Open Atone" })
vim.keymap.set("n", "<leader>j", ":wincmd j<CR>", { desc = "Window down" })
vim.keymap.set("n", "<leader>k", ":wincmd k<CR>", { desc = "Window up" })
vim.keymap.set("n", "<leader>h", ":wincmd h<CR>", { desc = "Window left" })
vim.keymap.set("n", "<leader>l", ":wincmd l<CR>", { desc = "Window right" })
vim.keymap.set("n", "<leader>\\", ":vsplit<CR>", { desc = "Vertical split" })
vim.keymap.set("n", "<leader>-", ":split<CR>", { desc = "Horizontal split" })
vim.keymap.set('n', '<leader>d', vim.diagnostic.open_float, { desc = 'Show diagnostic message' })
vim.keymap.set({"n", "i"}, "<C-S>", ":w<CR>", { desc = "Save file" })
vim.keymap.set("n", "<M-w>", "<C-W>", { noremap = true, silent = true, desc = "Window commands" })
vim.keymap.set("n", "<F5>", function() require('dap').continue() end, { desc = "DAP continue" })
vim.keymap.set("n", "<F10>", function() require('dap').step_over() end, { desc = "DAP step over" })
vim.keymap.set("n", "<F11>", function() require('dap').step_into() end, { desc = "DAP step into" })
vim.keymap.set("n", "<F12>", function() require('dap').step_out() end, { desc = "DAP step out" })
vim.keymap.set("n", "<Leader>b", function() require('dap').toggle_breakpoint() end, { desc = "Toggle breakpoint" })
vim.keymap.set("n", "<F4>", function() require('dapui').toggle() end, { desc = "Toggle DAP UI" })
vim.keymap.set('n', 'sf', require('telescope.builtin').find_files, { desc = '[S]earch [F]iles' })
vim.keymap.set('n', 'rg', require('telescope.builtin').live_grep, { desc = '[S]earch by [G]rep' })
vim.keymap.set('n', '<leader>?', require('telescope.builtin').oldfiles, { desc = '[?] Find recently opened files' })
vim.keymap.set('n', '<leader><space>', require('telescope.builtin').buffers, { desc = '[ ] Find existing buffers' })
vim.keymap.set("n", "gd", require('telescope.builtin').lsp_definitions, { desc = "Go to definition" })
vim.keymap.set("", "X", "x", { noremap = true, desc = "Delete char under cursor" })

-- Commands
vim.api.nvim_create_user_command("Q", "q", {})
vim.api.nvim_create_user_command("W", "w", {})
vim.api.nvim_create_user_command("Qa", "qa", {})
